# GitOps Manifest
# Change the tag to deploy a new version
# GitHub Actions will automatically deploy when this file changes

web:
  image: ghcr.io/sbozh-me/website
  tag: 0.11.7

pdf-generator:
  image: ghcr.io/sbozh-me/pdf-generator
  tag: 0.11.7
